### ISSUE TITLE
[Enhancement] Improve error handling with invalid query

### ISSUE THREAD

**Issue by MrKotov** [kepelrs/nestjs-prisma-crud#2]
# Steps to reproduce

1. Init project with flat model (no relations required) and expose getMany endpoint
2. Send crudQ formatted request containing 'contains' operato:
```
	where: {
		someValidField: { contains: { notallowedFormat: 'but lets try' } }
       }

```

## Current result
Server responds with 403 Forbidden which made me re-visit docs and config (I don't have any Access Policies setup). However it has nothing to do with them but with the invalid query.

## Expected result
I would expect having a 500 or 400 server response due to the incorrect request being sent.

**Comment by kepelrs** [comment]
Hi, I just changed the 403 to 400 in the latest release. Thanks for the feedback.
