### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by abdelrahman-osama** [kepelrs/nestjs-prisma-crud#202]
Regardless of what I write in a query. The GET request ignores it and returns everything with the default parameters. This is the case with all types of input parameters. Any idea what is causing that?
![Screen Shot 2022-06-14 at 8 05 56 PM](https://user-images.githubusercontent.com/18384535/173658920-a5e2cef7-69f0-4162-a709-6c3233470895.png)

**Comment by kepelrs** [comment]
Hi. You must pass the entire crudQuery as json string under the `?crudQuery=jsonString` [as seen here](https://kepelrs.github.io/nestjs-prisma-crud/client-side#tldr-usage). This is [not the only way](https://kepelrs.github.io/nestjs-prisma-crud/client-side#overview) to do it but it's the most recommended as it's the easiest and most flexible.
