### ISSUE TITLE
support more package manager or manually install

### ISSUE THREAD

**Issue by superiums** [kepelrs/nestjs-prisma-crud#218]
after execute this command , npm was used to install packages.
but , i'm using pnpm.
could you add support with it ? Or just let user install packages manually.

``` nest g -c nestjs-prisma-crud-schematics crud-resource post ```

**Comment by kepelrs** [comment]
The schematics package is a minimal effort fork and adaptation of [nest's original schematics](https://github.com/nestjs/schematics) and I do not intend to add any features to it.

If you really need this, I suggest you submit an issue or pull request on their repo, and we will inherit the functionality when pulling upstream :)
