### ISSUE TITLE
[Feature] option to compare context instead of role hard code

### ISSUE THREAD

**Issue by superiums** [kepelrs/nestjs-prisma-crud#225]
It's common to compare usr.roles with accessRequired roles.
but i think it's more flexiable and convenient to compare usr.priviledge with controller name and method name.

### why ?
- if write accessRequired roles in decorator, it's hard code, not manageable on frontend.
- if compare priviledges, it's more flexiable, because one user may has many roles, one role may has many priviledges.
- if we use priviledges, this information is already there in controller. both class and handler method could be found by ctx. so we may use accessGuard on controller or gloabal.

### example

> in controller:
```
@accessGuard                // same as @accessGuard('CatsController.*')
@controller('cats')
class CatsController....
        create().....
        delete().....

```

> in appModule.ts
```
@Module({
  imports: [
   
    PrismaCrudModule.register({
      accessControl: {
        compareTo: 'context',   // handler and class
        authDataKey: 'user',
        getRolesFromAuthDataFn: (authenticatedUser) => authenticatedUser?.priviledges,
        strict: false,
      },
    }),
  ]
})
```

> user.priviledges:
```
//extracted from all roles:
[
  'CatsController.create',
  'someController.delete',
  '*.read',
  'some.*'
]
** it's better to support wildcard **
```

in accessGuard we compare user.priviledges With the context ( handler and class).

so we haven't to specify accessGuard on every api. also it's more flexiable to handle acess with complex situations. more convenient and flexiable.

**Comment by kepelrs** [comment]
I agree this authorization pattern has many benefits. Can this not be implemented by using [Custom Policies](https://kepelrs.github.io/nestjs-prisma-crud/access-control-module/custom-policy)? I don't have plans to include this into the package.

Writing a custom policy is easy: it is just a function which will receive the ExecutionContext, AuthData and ModuleRef. Sounds to me like the first two should contain all the info you need :) See [examples](https://kepelrs.github.io/nestjs-prisma-crud/access-control-module/custom-policy#dbbannedpeople-policy).

You would need to use `'everyone'` to bypass the RBAC (first argument to the `AccessPolicy`). I plan on making that optional with upcoming changes.
```typescript
// Top level AccessPolicy should also be supported, but still needs tests and documentation
// @AccessPolicy('everyone', CheckPrivileges) 
@Controller('party')
export class PartyController {
    @Get()
    @AccessPolicy('everyone', CheckPrivileges)
    async getParties(@Query('crudQuery') crudQuery: string) {
        const matches = await this.partyService.findMany(crudQuery);
        return matches;
    }
}
```

**Comment by superiums** [comment]
> Can this not be implemented by using [Custom Policies](https://kepelrs.github.io/nestjs-prisma-crud/access-control-module/custom-policy)?

thanks, this is a good idea too!
