### ISSUE TITLE
Unable to find .prisma/client

### ISSUE THREAD

**Issue by darr1s** [kepelrs/nestjs-prisma-crud#455]
Hi there! Thanks for the repo.

Anyways I bumped into this issue here, and I'm not sure if its intentional to import from `.prisma/client` or if its an issue with pnpm linking.

https://github.com/kepelrs/nestjs-prisma-crud/blob/2a89f7b24441c009e2abc45e7ccb52065f0ffb68/src/crud/prisma-crud.service.ts#LL1-L1C47

![image](https://user-images.githubusercontent.com/21124691/229883067-b27f1614-eabd-41ac-b0d6-92ff85728fb7.png)

**Comment by kepelrs** [comment]
Thanks, this was probably unintentional IDE autocomplete. 

It is fixed in the [beta-17](https://github.com/kepelrs/nestjs-prisma-crud/releases/tag/v1.0.0-beta.17). Let me know if you still have issues after upgrade :)
