### ISSUE TITLE
Bug: Datetime fields does not show on the response

### ISSUE THREAD

**Issue by hacKarim** [kepelrs/nestjs-prisma-crud#550]
When dealing with datetime, the query returns the datetime field as an empty object.

for example
  created DateTime? @default(now())

returns 
  created: {}

I'm on nestjs (latest), prisma (latest)

**Comment by kepelrs** [comment]
Hey! I'm not able to reproduce this issue, the date is showing up just fine in the response. 

What db are you using? Could it be caused by something else in your code base? If not, I may need minimal reproduction repo.

**Comment by hacKarim** [comment]
Sorry for the late reply, my bad. It was indeed something else that triggered the issue.
I'm closing the Issue

**Comment by kepelrs** [comment]
Thanks for the update!
