### ISSUE TITLE
Question: Skip endpoints creation & Genric DTO

### ISSUE THREAD

**Issue by morplo-developer** [kepelrs/nestjs-prisma-crud#646]
Description:

- i don't want to render all CRUD endpoints
- i want to display generic DTO in my POST body

Will it be possible to have those features?

**Comment by kepelrs** [comment]
> i don't want to render all CRUD endpoints

Do you mean you want the CRUD schematic not to generate all GET/POST/PATCH/DELETE endpoints? If so, the answer is no, we won't add that feature. It is simple enough to just generate the controller and then delete the endpoints you don't want to use.

> i want to display generic DTO in my POST body

I don't understand this. Your POST response can be anything you want, you are not obligated to return the created object.

**Comment by morplo-developer** [comment]
@kepelrs  thanks!
