### ISSUE TITLE
Help: Two Register Modules in one Project

### ISSUE THREAD

**Issue by linsua01** [kepelrs/nestjs-prisma-crud#666]
Hello, I am trying to access to two databases in the same project, I have already managed to configure prisma for the different schemes, but I cannot configure prismaCrudModule.register for both prisma Clients, is it possible to do this?

**Comment by kepelrs** [comment]
I don't think it is currently possible for you to register two prisma clients. However, you can register a primary one in PrismaCrudModule.register, and whenever you need to use the other one you can simply provide it in the `super` call of the service constructor (see https://kepelrs.github.io/nestjs-prisma-crud/crud-endpoints#crud-service)

**Comment by linsua01** [comment]
Thank you Kepelrs,

Yes, it is working, thank you a lot!

You have to add NEW to instance the class! :)

I got a TS warning, do you now who I can fix it? please check attached image!

```
@Injectable()
export class OrdersService extends PrismaCrudService {
  constructor() {
    super({
      //@ts-ignore
      prismaClient: new PrismaFTService, // -> provide alternative prismaClient here
      model: 'orders',
      allowedJoins: [],
      defaultJoins: [],
![Uploading Captura de pantalla 2023-11-27 a las 16.19.32.png…]()

    });
  }
}
```

**Comment by kepelrs** [comment]
I suspect you just forgot to call the new instance. 

```typescript
@Injectable()
export class OrdersService extends PrismaCrudService {
  constructor() {
    super({
      //@ts-ignore                              --> remove this, it is very likely to shoot you in the foot
      prismaClient: new PrismaFTService(), //   --> just added "()" to instantiate the new class
      model: 'orders',
      allowedJoins: [],
      defaultJoins: [],
    });
  }
}
```

Note that if you plan to do this in multiple services, calling `new PrismaFTService()` in many places is not the best idea as it potentially initialises a large number of connections to the database, which can be a problem depending on your specific setup. If this concern applies to you, consider creating a global NestJS module which creates only one global instance of your `PrismaFTService` and then you can inject it in your `OrdersService`.
