### ISSUE TITLE
Crud for model with JSON property not working (provided nested relation is not allowed)

### ISSUE THREAD

**Issue by bieblebrox** [kepelrs/nestjs-prisma-crud#708]
Hi,

I'm trying out this CRUD generation service and hit a bit of a blocker:

This is my simple prisma model:

```
model Label {
  id           String   @id @default(cuid())
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  name         String
  data         Json
}
```

I've followed the steps to set up the crud controller and it automatically created a label module.
However, when I fire a request:

```
curl --request POST \
  --url http://localhost:3000/label \
  --header 'content-type: application/json' \
  --data '{
  "name": "Testing",
  "data": {
    "someprop": "somval"
  }
}'
```

It returns the following error:

```
{
  "message": "Provided nested relation is not allowed: data",
  "error": "Bad Request",
  "statusCode": 400
}
```

You can see it's complaining about the JSON object.
When I try to create a new label from PrismaClient directly, there is no problem.

Not sure if this is a bug or a security feature on the crud controller?

**Comment by kepelrs** [comment]
Hi! Json fields are not supported at the moment. This is described in the [Limitations](https://kepelrs.github.io/nestjs-prisma-crud/limitations) section of the docs.

The suggested workaround at the moment is to store the JSON object as a string.
