### ISSUE TITLE
Limit joins

### ISSUE THREAD

**Issue by khalibloo** [kepelrs/nestjs-prisma-crud#752]
There doesn't seem to be a way to limit joins. It will simply return all of the linked relations, even if there are thousands of them. It would be nice to be able to set a limit at least, effectively a pageSize. Even better if we can order them as well.

**Comment by kepelrs** [comment]
Hi. If you have a `/post/postId1?join=comment` (pseudo url) which yields thousands of comments, then you should send a GET request to `/comment?where=post.id==postId1` instead (pseudo url). This way you will be getting all the filtering/sorting/pagination capabilities for the comments.

Additional filtering for relations is not going to be supported by this lib. The goal here is to keep it simple by staying within a typical REST architecture and only some small convenience on top. 

For more specific queries you should consider going for something like graphql, or having special utility endpoints in your backend.
